### ISSUE TITLE
ResourceLoader module `targets` has been removed in MW 1.42

### ISSUE THREAD

**Issue by R4356th** [alex4401/mediawiki-extensions-ThemeToggle#23]
It was deprecated in 1.41. See https://phabricator.wikimedia.org/T340802.

**Comment by alex4401** [comment]
Thanks. The earliest this can be handled is once wiki.gg finishes their 1.41 upgrade, and 1.39 support here can be dropped. I'd rather not maintain different release trees.

**Comment by alex4401** [comment]
Done on REL1_41 with 5dcc6c80dd5ff1a147d85a5b7746d5186fef6d9f.
