### ISSUE TITLE
`rights=`-constrained themes aren't listed in the theme switcher

### ISSUE THREAD

**Issue by GoboZen** [alex4401/mediawiki-extensions-ThemeToggle#26]
Adding any required rights to a theme disables it in every case, regardless of the user's rights.
The user right verification is not implemented (unfinished), does not match the required rights to the available rights.

https://github.com/alex4401/mediawiki-extensions-ThemeToggle/blob/6ab7cfe96f9a90d935e768cfd57c61486697efe6/includes/Hooks/ThemeLoadingHooks.php#L196
`count( $themeInfo->getRequiredUserRights() ) <= 0`

I'd suggest only checking for one user right for simplicity of the code and configuration. I don't see requiring the intersection of more rights to be a practical use-case, since on small/medium wikis users with more rights tend to have all the less powerful rights.

**Comment by alex4401** [comment]
Those themes are disabled from the switchers, but they should still be available through Special:Preferences.

**Comment by alex4401** [comment]
Starting work on this in a few minutes. Updated the issue's title as needed.

Right checks have already been implemented in ThemeInfo::isUserAllowedToUse (https://github.com/alex4401/mediawiki-extensions-ThemeToggle/blob/4361e9d/includes/Data/ThemeInfo.php#L80).

**Comment by alex4401** [comment]
Done in v1.2.0. Deployment pending on wiki.gg.
